// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultispatialLogistics.Core3.Models;

namespace MultispatialLogistics.Core3.Migrations
{
    [DbContext(typeof(MultispatialLogisticsContext))]
    partial class MultispatialLogisticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultispatialLogistics.Core3.Models.Stargate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DestinationStargateId");

                    b.Property<int>("DestinationSystemId");

                    b.Property<int>("ParentSystemId");

                    b.Property<string>("ParentSystemName");

                    b.Property<int>("StargateId");

                    b.Property<long>("XPos");

                    b.Property<long>("YPos");

                    b.Property<long>("ZPos");

                    b.HasKey("Id");

                    b.ToTable("Stargate");
                });
#pragma warning restore 612, 618
        }
    }
}
